
DUB_PACKAGES = backtrace-d-master/source \
               dyaml-0.5.0/source \
               tinyendian-0.1.1/source


JSWFILES = src/jaypha/spinna/pagebuilder/widgets/string.js \
           src/jaypha/spinna/pagebuilder/widgets/integer.js \
           src/jaypha/spinna/pagebuilder/widgets/boolean.js \
           src/jaypha/spinna/pagebuilder/widgets/enum.js \
           src/jaypha/spinna/pagebuilder/widgets/datepicker.js \
           src/jaypha/spinna/pagebuilder/widgets/dropdown_list.js \
           src/jaypha/spinna/pagebuilder/widgets/autofill.js \
           src/jaypha/spinna/pagebuilder/widgets/decimal.js \
           src/jaypha/spinna/pagebuilder/widgets/calendar.js \
           src/jaypha/spinna/pagebuilder/widgets/dialog_box.js \
           src/jaypha/spinna/pagebuilder/widgets/selector.js \
           src/jaypha/spinna/pagebuilder/widgets/form.js \
           src/jaypha/spinna/pagebuilder/widgets/dynamic_widgets.js \
           src/jaypha/spinna/pagebuilder/widgets/icon.js \
           src/jaypha/spinna/pagebuilder/widgets/icon_button.js \
           src/jaypha/spinna/pagebuilder/widgets/wide_button.js \
           src/jaypha/spinna/pagebuilder/widgets/tabbed.js \
           src/jquery/jquery-ui.js \
           thirdparty/jquery/jquery.caret.js \
           src/jaypha/spinna/pagebuilder/form_fragment/std_layout.js \

JSFILES = src/jaypha/common.js \
          thirdparty/js_date_format/js_date_format.js

SCSSWFILES = src/jaypha/spinna/pagebuilder/widgets/widgets.scss \
             src/jaypha/spinna/pagebuilder/widgets/calendar.scss \
             src/jaypha/spinna/pagebuilder/widgets/dialog_box.scss \
             src/jaypha/spinna/pagebuilder/widgets/icon.scss \
             src/jaypha/spinna/pagebuilder/widgets/icon_button.scss \
             src/jaypha/spinna/pagebuilder/widgets/wide_button.scss \
             src/jaypha/spinna/pagebuilder/widgets/toolbar_ex.scss \
             src/jaypha/spinna/pagebuilder/widgets/tabbed.scss \

SCSSFILES = 
